Harvest/farmcon/farmcon/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from products.views import single_product, search, home_view
from orders.views import checkout, orders
from accounts.views import (logout_view, login_view, 
                            register_view, farmer_view, 
                            buyer_view, verify_number, send_code,
                            update_profile,user_profile, email_sent,
                            activate_email)

urlpatterns = [
    path('admin/', admin.site.urls), #admin view

    #views from products app
    path('', home_view, name='home'),
    path('product/<str:slug>/', single_product, name='single_product'),
    path('s/', search, name='search'),

    #views from order app
    path('orders/', orders, name='user_orders'),
    path('checkout/', checkout, name='checkout'),

    #views from account app
    path('logout/', logout_view, name='logout'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('farmer/', farmer_view, name='farmer'),
    path('buyer/', buyer_view, name='buyer'),
    path('verify/', verify_number, name='verify_number'),
    path('send_code/', send_code, name='send_code'),
    path('update/', update_profile, name='update_profile'),
    path('profile/', user_profile, name='user_profile'),
    path('email_sent/', email_sent, name='email_sent'),
    path('activate_email/<uidb64>/<token>/', activate_email, name='activate_email'),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='account/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='account/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='account/password_reset_form.html'), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='account/password_reset_complete.html'),
     name='password_reset_complete'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Harvest/farmcon/products/models.py
from django.db import models

# Create your models here.
class Product(models.Model):
	title = models.CharField(max_length=120, null=False, blank=False)
	description = models.TextField()
	price = models.DecimalField(decimal_places=2, max_digits=10, default=0.0)
	slug = models.SlugField(unique=True)
	date_created = models.DateTimeField(auto_now_add=True, auto_now=False)
	date_updated = models.DateTimeField(auto_now_add=False, auto_now=True)
	quantity = models.IntegerField(default=10)
	in_stock = models.BooleanField(default=True)


	def __str__(self):
		return self.title

	class Meta:
		unique_together = ('title', 'slug')

	def get_price(self):
		return self.price


class ProductImage(models.Model):
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	image = models.ImageField(upload_to='products/images/')
	featured = models.BooleanField(default=False)
	thumbnail = models.BooleanField(default=False)
	active = models.BooleanField(default=True)
	date_updated = models.DateTimeField(auto_now_add=False, auto_now=True)

	def __str__(self):
		return self.product.title

Harvest/farmcon/templates/general/buyer.html
<a href="{% url 'home' %}">Home</a>
<hr>
<h1>Buyer page</h1>
{% if not user.phone_verify %}
	<a href="{% url 'send_code' %}">Verify Phone Number</a>
{% endif %}
<a href="{% url 'logout' %}">Logout</a>
<a href="{% url 'update_profile' %}">Update Profile</a>
<a href="{% url 'user_profile' %}">Profile</a>

Harvest/farmcon/templates/general/farmer.html
<a href="{% url 'home' %}">Home</a>
<hr>
<h1>Farmer page</h1>
{% if not user.phone_verify %}
	<a href="{% url 'send_code' %}">Verify Phone Number</a>
{% endif %}
<a href="{% url 'logout' %}">Logout</a>
<a href="{% url 'update_profile' %}">Update Profile</a>
<a href="{% url 'user_profile' %}">Profile</a>

Harvest/farmcon/templates/general/home.html
<head>
	<link rel="icon"
      type="image/png"
      href="/favicon.ico">
</head>

<form action="/s/" autocomplete="off">
	<div>
		<input type="text" name="q" placeholder="Search">
	</div>
	<button type="submit">Submit</button>
</form>


{% if user.is_authenticated %}
	<a href="{% url 'logout' %}">Logout</a>
	<a href="{% url 'update_profile' %}">Update Profile</a>
	<a href="{% url 'user_profile' %}">Profile</a>
	{% if user.status == 'Farmer' %}
		<a href="{% url 'farmer' %}">My products page</a>
	{% else %}
		<a href="{% url 'buyer' %}">My products page</a>
	{% endif %}
{% else %}
	<a href="{% url 'login' %}">Login</a>
	<a href="{% url 'register' %}">Register</a>
{% endif %}

<br>

{% for product in products %}
	{{ product.id }}
	<a href="{% url 'single_product' product.slug %}">{{ product.title }}</a>
	{{ product.price }}
	{{ product.slug }}

	{% for item in product.productimage_set.all %}
		{% load static %}
		<img src="{{ MEDIA_URL }}{{ item.image }}" alt="My Image">
	{% endfor %}
{% endfor %}